--drop table TBL_NPS_PROJECT_RELACIONAL_CLIENTE

CREATE TABLE TBL_NPS_PROJECT_RELACIONAL_CLIENTE
(
	NUM_ID							INT NOT NULL IDENTITY(1,1),
	CHR_DATA_RESPOSTA				VARCHAR(500),
	CHR_PESQUISA					VARCHAR(500),
	CHR_SHOPPING					VARCHAR(500),
	CHR_NPS							VARCHAR(500),
	CHR_NPS_MELHORAR				VARCHAR(500),
	CHR_META10_MELHORAR				VARCHAR(500),
	CHR_INFLUENCIA_NOTA				VARCHAR(500),
	CHR_FREQUENCIA_SHOPPING			VARCHAR(500),
	CHR_COMENTARIO_SUGESTAO			VARCHAR(500),
	PRIMARY KEY(NUM_ID)
)

create table CatAPI
(
	CatId	varchar(10),
	CatName varchar(200)
)