// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPS_PROJECT_API.Data;

#nullable disable

namespace NPS_PROJECT_API.Migrations.PesquisaGeral
{
    [DbContext(typeof(PesquisaGeralContext))]
    partial class PesquisaGeralContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NPS_PROJECT_API.Models.PesquisaGeral", b =>
                {
                    b.Property<int>("NUM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NUM_ID"), 1L, 1);

                    b.Property<string>("col1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_DATA_RESPOSTA");

                    b.Property<string>("col10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_TECNOLOGIA_MELHORAR");

                    b.Property<string>("col11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_TECNOLOGIA_OUTROS");

                    b.Property<string>("col12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_PRACA_ALIMENTACAO");

                    b.Property<string>("col13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_PRACA_ALIMENTACAO_MELHORAR");

                    b.Property<string>("col14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_BANHEIRO");

                    b.Property<string>("col15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_BANHEIRO_MELHORAR");

                    b.Property<string>("col16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_ESTACIONAMENTO");

                    b.Property<string>("col17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_ESTACIONAMENTO_MELHORAR");

                    b.Property<string>("col18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_SEGURANCA");

                    b.Property<string>("col19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_SEGURANCA_MELHORAR");

                    b.Property<string>("col2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_PESQUISA");

                    b.Property<string>("col20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_CORREDORES");

                    b.Property<string>("col21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_CORREDORES_MELHORAR");

                    b.Property<string>("col22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_LOJAS");

                    b.Property<string>("col23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_LOJAS_MELHORAR");

                    b.Property<string>("col24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_ATENDIMENTO");

                    b.Property<string>("col25")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_ATENDIMENTO_MELHORAR");

                    b.Property<string>("col26")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_CINEMA");

                    b.Property<string>("col27")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_CINEMA_MELHORAR");

                    b.Property<string>("col28")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_LAZER");

                    b.Property<string>("col29")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_LAZER_MELHORAR");

                    b.Property<string>("col3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_SHOPPING");

                    b.Property<string>("col30")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_ACESSIBILIDADE");

                    b.Property<string>("col31")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_ACESSIBILIDADE_MELHORAR");

                    b.Property<string>("col32")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_FREQUENCIA");

                    b.Property<string>("col33")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_PERFIL_PESQUISA");

                    b.Property<string>("col34")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_COMENTARIO_SUGESTAO");

                    b.Property<string>("col4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_ORIGEM");

                    b.Property<string>("col5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_NPS");

                    b.Property<string>("col6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_NPS_COMENTARIO");

                    b.Property<string>("col7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_UTILIZA_TECNOLOGIA");

                    b.Property<string>("col8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_APP_MELHORAR");

                    b.Property<string>("col9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_APP_OUTROS");

                    b.HasKey("NUM_ID");

                    b.ToTable("TBL_NPS_PROJECT_PESQUISA_GERAL");
                });
#pragma warning restore 612, 618
        }
    }
}
