// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPS_PROJECT_API.Data;

#nullable disable

namespace NPS_PROJECT_API.Migrations
{
    [DbContext(typeof(RelacionalClienteContext))]
    [Migration("20220606214916_NPS_Migr_Relacional_Cliente")]
    partial class NPS_Migr_Relacional_Cliente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NPS_PROJECT_API.Models.RelacionalCliente", b =>
                {
                    b.Property<int>("NUM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NUM_ID"), 1L, 1);

                    b.Property<string>("col1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_DATA_RESPOSTA");

                    b.Property<string>("col2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_PESQUISA");

                    b.Property<string>("col3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_SHOPPING");

                    b.Property<string>("col4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_NPS");

                    b.Property<string>("col5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_NPS_MELHORAR");

                    b.Property<string>("col6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_META10_MELHORAR");

                    b.Property<string>("col7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_INFLUENCIA_NOTA");

                    b.Property<string>("col8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_FREQUENCIA_SHOPPING");

                    b.Property<string>("col9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHR_COMENTARIO_SUGESTAO");

                    b.HasKey("NUM_ID");

                    b.ToTable("TBL_NPS_PROJECT_RELACIONAL_CLIENTE");
                });
#pragma warning restore 612, 618
        }
    }
}
